### ISSUE TITLE
setTensorFlowEV.sh can't find deviceQuery

### ISSUE THREAD

**Issue by iandow** [jetsonhacks/installTensorFlowTX2#13]
setTensorFlowEV.sh is failing with the following error:

`./configure: line 669: /usr/local/cuda/extras/demo_suite/deviceQuery: No such file or directory`

**Comment by jetsonhacks** [comment]
deviceQuery is not located in the standard cuda location on the Jetson. The error can be safely ignored, as the environment variables are set in this shell file.

**Comment by mustafamerttunali** [comment]
How can I Ignore? There is no information about deviceQuery in this shell file(setTensorFlowEV.sh)?

**Comment by raghavgurbaxani** [comment]
Hi, I get the same error. Could you please explain how to deal with this? 

thanks
