### ISSUE TITLE
How to remove the swapfile

### ISSUE THREAD

**Issue by mpkuse** [jetsonhacks/installTensorFlowTX2#16]
My installation was incomplete due to lack of space on device. As I try to `rm ~/swapfile`, I get `Operation not Permitted`. Even tried as root. Didn't help. Any pointers on this?

**Comment by mpkuse** [comment]
Nevermind, I figured it out. Just reboot the device and rm the file. I reckon the swap may be in use so was not able to remove. 

Would nevertheless appreciate a solution without a reboot.

**Comment by ahmed-shariff** [comment]
you can use `swapoff` and then `rm`

**Comment by jetsonhacks** [comment]
Agreed, swapoff and then rm.
