### ISSUE TITLE
Unable to Install wheel file: pip install $HOME/tensorflow-1.0.1-cp27-cp27mu-linux_aarch64.whl

### ISSUE THREAD

**Issue by s3p02** [jetsonhacks/installTensorFlowTX2#18]
nvidia@tegra-ubuntu:~$ pip install tensorflow-1.3.0-cp27-cp27mu-linux_aarch64.whl 

**tensorflow-1.3.0-cp27-cp27mu-linux_aarch64.whl is not a supported wheel on this platform.**

**_I even tried sudo:_**

nvidia@tegra-ubuntu:~$ sudo pip install tensorflow-1.3.0-cp27-cp27mu-linux_aarch64.whl

_The directory '/home/nvidia/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nvidia/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag._
**tensorflow-1.3.0-cp27-cp27mu-linux_aarch64.whl is not a supported wheel on this platform.**

**Comment by jetsonhacks** [comment]
I don't know what kind of machine you are running on, what version of L4T or where you acquired the whl file.
