### ISSUE TITLE
Tensorflow r1.x for Jetson TX1

### ISSUE THREAD

**Issue by kiyoon** [jetsonhacks/installTensorFlowTX2#2]
Can bazel 0.4.5 be built on Jetson TX1?

I know that you have a script for TX1, but that doesn't install the latest version of tensorflow.
When I try to build bazel 0.4.5 with your script, it fails, which I don't understand.
Can you verify this? TX2 is also using 'aarch64' architecture, then why does it fail?

I think after building bazel, building tensorflow won't be hard since I already have CUDA 8.0 and CUDNN 5.1, installed with newest JetPack.

Error output is as follows:
```
scripts/bootstrap/compile.sh: line 316: 13922 Killed                  "${JAVA_HOME}/bin/java" -XX:+HeapDumpOnOutOfMemoryError -Xverify:none -Dfile.encoding=ISO-8859-1 -XX:HeapDumpPath=${OUTPUT_DIR} -Djava.util.logging.config.file=${OUTPUT_DIR}/javalog.properties ${JNI_FLAGS} -jar ${ARCHIVE_DIR}/libblaze.jar --batch --install_base=${ARCHIVE_DIR} --output_base=${OUTPUT_DIR}/out --install_md5= --workspace_directory=${PWD} --nofatal_event_bus_exceptions ${BAZEL_DIR_STARTUP_OPTIONS} ${BAZEL_BOOTSTRAP_STARTUP_OPTIONS:-} $command --ignore_unsupported_sandboxing --startup_time=329 --extract_data_time=523 --rc_source=/dev/null --isatty=1 --ignore_client_env --client_cwd=${PWD} "${@}"

ERROR: Could not build Bazel
```

Thank you so much for your effort with Jetson series.

**Comment by kiyoon** [comment]
I think it's due to the lack of memory. I'll try to set up swap

**Comment by jetsonhacks** [comment]
Thanks for the kind words. On the Jetson, "killed" almost always means that it ran out of memory. The issue with building TensorFlow v1 on the TX1 is an invalid opcode in the nvcc compiler, which has been fixed in the 27.1 releases. People have v1 running on the TX1 with workarounds, but with the TX1 moving to a 27.X release the convergence for the two seems pretty short.

See the article: http://www.jetsonhacks.com/2016/12/30/tensorflow-nvidia-jetson-tx1-development-kit/ for more info on setting up swap and freeing space.

**Comment by kwotsin** [comment]
Hi @jetsonhacks, do you think a pip file built for this platform might just work on the TX1? Also, I've followed your previous tutorial to flash Jetpack 2.3.1 to get started on TX1, before using the TF alpha ugly hack to get TF installed. If I were to flash it with Jetpack 3.0 to get 27.1 instead, will TF v1.x work? I require the newer operations in the later versions of TF for quantization purposes, so it would be really great if TF can be safely compiled on TX1.

**Comment by jetsonhacks** [comment]
My understanding is that it does not work on the TX1. There is an issue with the instructions that are issued by nvcc. JetPack 3.0 installs the same L4T version as JetPack 2.3.1 on the TX1, L4T 27.1 is only available on the TX2.
