### ISSUE TITLE
Bazel installation Error for Python 2.7 in "/installPrerequisites.sh" command

### ISSUE THREAD

**Issue by zkhodzhaev** [jetsonhacks/installTensorFlowTX2#26]
![screenshot from 2018-07-31 15-21-01](https://user-images.githubusercontent.com/21960382/43514042-d30e8e60-956e-11e8-809b-d8a5a824fd19.png)
![screenshot from 2018-07-31 15-22-19](https://user-images.githubusercontent.com/21960382/43514058-d956b4dc-956e-11e8-8896-e5f54758f919.png)
![screenshot from 2018-07-31 15-19-39](https://user-images.githubusercontent.com/21960382/43514067-dc9b9b12-956e-11e8-9b4b-a39716da1d41.png)

My machine: Jetson TX2
                     Ubuntu 16.04 LTS
                     Python 2.7.12
                     CUDA  release 9.0, V9.0.252
                     cuDNN 7.0.5
Any clue ?

**Comment by jetsonhacks** [comment]
The installation scripts were written some time ago, when TensorFlow did not support CUDA 9.0. The issue is that an older version of JAVA is needed to build Bazel. For a more modern build, please see: https://github.com/JasonAtNvidia/JetsonTFBuild
