### ISSUE TITLE
From  V1.0.1 to V1.1.0?

### ISSUE THREAD

**Issue by aimuch** [jetsonhacks/installTensorFlowTX2#3]
There is something with TF v1.0.1, I want to update it.
If I change the follow files, can it works? Whether I need to uninstall the former vision?
1. cloneTensorFlow.sh
`git checkout v1.1.0`
2. packageTensorFlow.sh
`mv /tmp/tensorflow_pkg/tensorflow-1.0.1-cp27-cp27mu-linux_aarch64.whl $HOME/
`

**Comment by jetsonhacks** [comment]
I haven't tried it, so I don't know what issues you may encounter.
