### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by roryw10** [jetsonhacks/installTensorFlowTX2#4]
Hi 

Followed instructions exactly as directed but running into an error when building TF

INFO: From Compiling tensorflow/core/kernels/tile_ops_gpu.cu.cc:
Killed
ERROR: /home/ubuntu/tensorflow/tensorflow/core/kernels/BUILD:685:1: output 'tensorflow/core/kernels/_objs/tile_ops_gpu/tensorflow/core/kernels/tile_ops_gpu.cu.pic.o' was not created.
ERROR: /home/ubuntu/tensorflow/tensorflow/core/kernels/BUILD:685:1: not all outputs were created or valid.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
ERROR: /home/ubuntu/tensorflow/tensorflow/tools/pip_package/BUILD:103:1 not all outputs were created or valid.

any help would be much appreciated!

**Comment by jetsonhacks** [comment]
It looks like you ran out of memory. Is your swap file large enough?

**Comment by roryw10** [comment]
sorry my mistake - i didnt see the note to build the swapfile - i did manage to get it set up following instructions from

https://syed-ahmed.gitbooks.io/nvidia-jetson-tx2-recipes/content/first-question.html

now i'm having some issues with protobuf when running my script 

Using TensorFlow backend.
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.1.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1. Please update your library. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "external/protobuf/src/google/protobuf/any.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
what(): This program requires version 3.1.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1. Please update your library. If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. (Version verification failed in "external/protobuf/src/google/protobuf/any.pb.cc".)
Aborted (core dumped)

I'm going to try and run your setup again to see if this resolves the issue!

**Comment by moiseevigor** [comment]
@roryw10 did you managed to understand the error

```
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.1.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.
```

Thanks!
