### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dheera** [jetsonhacks/installTensorFlowTX2#6]
![screenshot from 2017-06-14 01-34-35](https://user-images.githubusercontent.com/1786477/27111755-24ea4b46-5067-11e7-9c71-130a9426a2a4.png)

**Comment by elirex** [comment]
This problem seem like the out of memory when compile.
You can try [this](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04) to add the swap.

**Comment by jetsonhacks** [comment]
This looks like an out of memory error. I believe that elirex proposes a good change. Please reopen if the issue continues.
