### ISSUE TITLE
Can this repository be used on tx1 for compiling tf1.0.1?

### ISSUE THREAD

**Issue by dattasaurabh82** [jetsonhacks/installTensorFlowTX2#8]
Can this repository be used on tx1 for compiling tf1.0.1? what changes need to be made if nay needed?

**Comment by JonathanJenk** [comment]
I used the TX1 setup with an older version on the TX2, the only changes needed were in the out of date urls to downloads. 

I may try this, if you haven't already?

**Comment by jetsonhacks** [comment]
Hopefully you got it to work. Basically the major change is the CUDA compute needs to change from 6.2 for the TX2 and the 5.3 for the TX1.
